<?php
/**
 * This file is part of
 * pragmaMx - Web Content Management System.
 * Copyright by pragmaMx Developer Team - http://www.pragmamx.org
 *
 * pragmaMx is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * $Revision: 6 $
 * $Author: PragmaMx $
 * $Date: 2015-07-08 09:07:06 +0200 (Mi, 08. Jul 2015) $
 */

defined('mxMainFileLoaded') or die('access denied');
define("_ACTIVATE2", "Activate?");
define("_ADDHEADLINE", "Add headline");
define("_ADDNEWBLOCK", "Add block");
define("_ARESUREDELBLOCK", "Are you sure you want to remove thís block");
define("_BLK_MODULE", "Module");
define("_BLOCK", "Block");
define("_BLOCKACTIVATION", "Block activation");
define("_BLOCKCACHEMSG", "If you set value here, the html-code generated by this block will be cached this time. Only use this function for blocks which do not need to be refreshed everytime and/or contain secret informations.");
define("_BLOCKDELCACHE", "Reset block cache");
define("_BLOCKFILE", "(Block file)");
define("_BLOCKFILE2", "FILE");
define("_BLOCKINSYSTEM", "Blocks marked with <b>*</b> allready exist in the system.");
define("_BLOCKNOBLOCKS", "There are no blocks for this view.");
define("_BLOCKORDER", "Order");
define("_BLOCKPREVIEW", "This is the preview for block");
define("_BLOCKSADMIN", "Blocks Administration");
define("_BLOCKSAVEORDER", "Save order");
define("_BLOCKSHOWACTIVE", "Active");
define("_BLOCKSHOWDEACTIVE", "Inactive");
define("_BLOCKS_INSTALLEDLIST", "installed blocks");
define("_BLOCKTITLE", "Title");
define("_CACHING", "Caching");
define("_CENTERDOWN", "Center bottom");
define("_CENTERUP", "Center top");
define("_CREATEBLOCK", "Create block");
define("_CUSTOM", "Custom");
define("_EDITBLOCK", "Edit block");
define("_EDITHEADLINE", "Edit headline");
define("_FILENAME", "Filename");
define("_FIXBLOCKS", "Fix block's weight conflicts");
define("_HEADLINESADMIN", "Headlines administration");
define("_LEFT", "Left");
define("_MINUTES", "Minutes");
define("_MVADMIN", "Administrators Only");
define("_MVALL", "All Visitors");
define("_MVANON", "Anonymous Users Only");
define("_MVGROUPS", "Special Usergroups Only");
define("_MVGROUPS2", "Usergroups Only");
define("_MVSYSADMIN", "System-Administrators only");
define("_NEVER", "never");
define("_POSITION", "Position");
define("_REFRESHTIME", "Refresh time");
define("_RIGHT", "Right");
define("_RIGHTNEWS", "Right (News)");
define("_RSSCONTENT", "(RSS/RDF content)");
define("_RSSFAIL", "There is a problem with the RSS file URL");
define("_RSSFILE", "RSS/RDF file URL");
define("_RSSTRYAGAIN", "Please check URL and RSS file name and try again.");
define("_SAVEBLOCK", "Save block");
define("_SETUPHEADLINES", "(Select 'Custom' and write the URL or just select a site from the list to grab news headlines)");
define("_SETUP_HEADLINES", "New / edit");
define("_SITENAME", "Site Name");
define("_STATUS", "Status");
define("_SURE2DELHEADLINE", "WARNING: Are you sure you want to delete this headline?");
define("_TYPE", "Type");
define("_URL", "URL");
define("_VIEWPRIV", "Who can View This?");
define("_WANT2ACTIVATE", "Do you want to activate this block?");
define("_WEIGHT", "Order");
define("_BLOCKSYSTEM", "SYSTEM");
define("_BLOCKFILEMISSED", "file missing");

?>